### ISSUE TITLE
Mangled name collision with clang 3.9.1

### ISSUE THREAD

**Issue by xanlpz** [Microsoft/ChakraCore#1989]
Getting this in debug builds with clang 3.9.1:

/home/xan/git/ChakraCore/lib/Runtime/ByteCode/ByteCodeDumper.cpp:1192:21: error: definition with same mangled name as another definition
    ByteCodeDumper::DumpReg2(OpCode op, const unaligned T * data, FunctionBody * dumpFunction, ByteCodeReader& reader)
                    ^
/home/xan/git/ChakraCore/lib/Runtime/ByteCode/LayoutTypes.h:47:1: note: previous definition is here
LAYOUT_TYPE_PROFILED_WMS    (Reg2)
^
/home/xan/git/ChakraCore/lib/Runtime/./ByteCode/ByteCodeDumper.h:57:9: note: expanded from macro 'LAYOUT_TYPE_PROFILED_WMS'
        LAYOUT_TYPE_WMS(layout) \
        ^
/home/xan/git/ChakraCore/lib/Runtime/./ByteCode/ByteCodeDumper.h:36:36: note: expanded from macro 'LAYOUT_TYPE_WMS'
    template <class T> static void Dump##layout(OpCode op, const unaligned T* data, FunctionBody * dumpFunction, ByteCodeReader& reader);
                                   ^
<scratch space>:117:1: note: expanded from here
DumpReg2
^

If I understand this right the collision seems to be between the methods in ByteCodeDumper and the static methods generated by the macros in the header, which apparently end up having the same mangled name and make clang unhappy.

**Comment by obastemur** [comment]
@xanlpz Thanks for the details. Already fixed under https://github.com/Microsoft/ChakraCore/pull/1930 .
