### ISSUE TITLE
Linux build is missing symbols as it is impossible to link to the shared library

### ISSUE THREAD

**Issue by lemmel** [Microsoft/ChakraCore#2859]
Hi.
I am in the need of a JS engine, and as ChakraCore looks simpler to embed than google's one (I need the debug features), I tried to build an application with it.

The build of the library itself did perform well. But when I try the Hello World [Sample](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Linux_OSX_Shared), I get:
`../out/Release/libChakraCore.so : undefined reference to « Js::WasmLibrary::WasmDeferredParseEntryPoint(Js::RecyclableObject*, Js::CallInfo, ...) »`

I succeeded to build a program in « static mode » or with the 1.4 branch.

Build informations:
- ChakraCore Version: the master branch (bfc4da44e3f9560c72bf87aad9f63b8fcdd5cd16)
- OS: Debian testing
- kernel: 4.9.0-2-amd64  (SMP Debian 4.9.18-1)
- arch: amd64
- target: Release Shared
- main libraries/tools:  

component | version/info
-------------- | --------------
libc6 | 2.24-9
libstdc++6 | 6.3.0-12
gcc-6 | 6.3.0-12

**Comment by obastemur** [comment]
@lemmel That `new` sample should work with `release/2.0`

**Comment by obastemur** [comment]
> I am in the need of a JS engine, and as ChakraCore looks simpler to embed than .....

I'm a ChakraCore project member. However, I did spend couple of years with other Javascript engines and embedded them into a node.js size project prior to working in this project. 

I have to say, regardless from my connection with the project, ChakraCore is indeed easiest to embed and use among the others.

Performance wise, ChakraCore performs well on Windows and we are close to catch that performance on other platforms.

We are close to our `first` cross platform release which is 2.0.0. So, if you are into using ChakraCore on other platforms, 2.0.0 should be the starting point.

**Comment by lemmel** [comment]
Hi @obastemur and thanks for the answer.

I can't find out the new sample, could you be more precise ?

As to my project, it is indeed a multi-plateform software; it used [QtScript](https://en.wikipedia.org/wiki/QtScript) from Qt, library that is now deprecated.
I'm wary and tired of the Qt's changes, and I prefer to invest some time on a external and lasting project.

So even though my program is a simple one, it may be a test for you as an multiplateform software. I hope I will be able to provide you useful informations.

**Comment by obastemur** [comment]
> I can't find out the new sample, could you be more precise ?

I mean, that sample is a `new sample project` that requires `release/2.0` instead of `1.4` version of ChakraCore.

> So even though my program is a simple one, it may be a test for you as an multiplateform software. I hope I will be able to provide you useful informations.

Let us know if you have any questions then. Closing this for now. Feel free to re-open if that sample project doesn't work with `release/2.0` branch.

Thanks!

**Comment by lemmel** [comment]
Sorry if I didn't me make clear enough: I did used the [Sample](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Linux_OSX_Shared) with a fresh cloned repo, and I did get the error message I posted above.

It is then/after that I build a « Hello World » (as I didn't find an sample for the 1.4 branch).

So basicaly, I wasn't successfull with the current sample and the current master.

**Comment by obastemur** [comment]
@lemmel The error you've been receiving was due to wrongly exported WASM declaration. I'm sending a PR very soon that fixes this issue and adds a test case so we don't end-up breaking again.

Thanks again!

**Comment by lemmel** [comment]
Thanks: the « Hello World » is now running.
I will next week on ChakraCore.
