### ISSUE TITLE
intrinsic redefinition with Clang-4.0

### ISSUE THREAD

**Issue by prazek** [Microsoft/ChakraCore#2892]
Hi,
The code fails to compile with new clang (I think after 4.0) with error like:
In file included from ../../pal/src/include/pal/thread.hpp:24:
In file included from ../../pal/src/include/pal/corunix.hpp:25:
In file included from ../../pal/src/include/pal/palinternal.h:323:
../../pal/inc/pal.h:6244:22: error: definition of builtin function '_rotl'
unsigned int __cdecl _rotl(unsigned int value, int shift)
                     ^
../../pal/inc/pal.h:6267:28: error: definition of builtin function '_rotl64'
unsigned long long __cdecl _rotl64(unsigned long long value, int shift)
                           ^
../../pal/inc/pal.h:6285:22: error: definition of builtin function '_rotr'
unsigned int __cdecl _rotr(unsigned int value, int shift)
                     ^
../../pal/inc/pal.h:6303:28: error: definition of builtin function '_rotr64'
unsigned long long __cdecl _rotr64(unsigned long long value, int shift)

This is because Clang-4.0 supports some of the microsoft intrinsics.
Probably fixes like this: https://github.com/dotnet/coreclr/pull/11226/files will be required

**Comment by obastemur** [comment]
Thanks for reporting, we will need couple of more feature detection in place.

**Comment by obastemur** [comment]
Fix is merged. @prazek Thank you for reporting this
