### ISSUE TITLE
Build on macOS 10.12 fails due to deprecated system call

### ISSUE THREAD

**Issue by Oceanswave** [Microsoft/ChakraCore#1927]
Steps to reproduce
---
Execute build steps as documented here:
https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore

Replacing
```
git checkout linux
```

with
```
git checkout release/1.3
```

Expected Behavior
---
Successful build of ChakraCore on macOS

Actual Behavior
---
The build fails with an error saying there's a call to a deprecated system call on macOS 10.12.

```
Scanning dependencies of target Chakra.Pal
[  0%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/file.cpp.o
[  1%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/filecrt.cpp.o
/ChakraCore/pal/src/cruntime/filecrt.cpp:355:12: error:
      'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is
      unsupported; please switch to a supported interface. For SYS_kdebug_trace
      use kdebug_signpost(). [-Werror,-Wdeprecated-declarations]
    nRet = syscall(SYS_delete, szPath);
           ^
/usr/include/unistd.h:733:6: note: 'syscall' has been explicitly marked
      deprecated here
int      syscall(int, ...);
         ^
1 error generated.
make[2]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/filecrt.cpp.o] Error 1
make[1]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by obastemur** [comment]
@Oceanswave this is a previously fixed issue on master branch. Thanks for reporting. Feel free to open it back in case fix doesn't work for you.
