### ISSUE TITLE
FunctionBody.cpp won't compile with clang >= 3.8.0

### ISSUE THREAD

**Issue by xanlpz** [Microsoft/ChakraCore#758]
A number of errors like this happen:
```

/home/xan/git/ChakraCore/lib/Runtime/Base/FunctionBody.cpp:1070:83: error: no matching constructor for initialization of 'Js::ProxyEntryPointInfo'
        this->m_defaultEntryPointInfo = RecyclerNew(scriptContext->GetRecycler(), ProxyEntryPointInfo, DefaultDeferredDeserializeThunk);
                                                                                  ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xan/git/ChakraCore/lib/Common/Memory/Recycler.h:117:88: note: expanded from macro 'RecyclerNew'
#define RecyclerNew(recycler,T,...) AllocatorNewBase(Recycler, recycler, AllocInlined, T, __VA_ARGS__)
                                                                                       ^  ~~~~~~~~~~~
/home/xan/git/ChakraCore/lib/Common/Memory/Allocator.h:83:206: note: expanded from macro 'AllocatorNewBase'
  ...alloc, AllocFunc, T, ...) VALIDATE_OBJECT(T, new (TRACK_ALLOC_INFO(static_cast<AllocatorType *>(alloc), T, AllocatorType, 0, (size_t)-1), &AllocatorType::AllocFunc) T(__VA_ARGS__))
                                                                                                                                                                          ^ ~~~~~~~~~~~
/home/xan/git/ChakraCore/lib/Common/Memory/Allocator.h:79:33: note: expanded from macro 'VALIDATE_OBJECT'
#define VALIDATE_OBJECT(T, obj) obj
                                ^~~
/home/xan/git/ChakraCore/lib/Runtime/Base/FunctionBody.h:314:11: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Var (Js::RecyclableObject *, Js::CallInfo, ...)'
      (aka 'void *(Js::RecyclableObject *, Js::CallInfo, ...)') to 'const Js::ProxyEntryPointInfo' for 1st argument
    class ProxyEntryPointInfo:  public ExpirableObject
          ^
/home/xan/git/ChakraCore/lib/Runtime/Base/FunctionBody.h:314:11: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'Var (Js::RecyclableObject *, Js::CallInfo, ...)'
      (aka 'void *(Js::RecyclableObject *, Js::CallInfo, ...)') to 'Js::ProxyEntryPointInfo' for 1st argument
/home/xan/git/ChakraCore/lib/Runtime/Base/FunctionBody.h:321:9: note: candidate constructor not viable: no known conversion from 'Var (Js::RecyclableObject *, Js::CallInfo, ...)'
      (aka 'void *(Js::RecyclableObject *, Js::CallInfo, ...)') to 'void *' for 1st argument
        ProxyEntryPointInfo(void* address, ThreadContext* context = nullptr):
```
There's a number of issues here. What the code is doing is trying to cast a pointer to a static member function to void*. This is in principle not allowed by the C++ standard. It's unclear why it works in older versions of clang (or VisualStudio?), but it fails in clang >= 3.8.

Another issue on top of that is that one of the ways the pointer to the static member function is used in ProxyEntryPointInfo is:

`        static DWORD GetAddressOffset() { return offsetof(ProxyEntryPointInfo, address); }`

According to the standard the behavior of offsetof for static members is undefined. So again this seems wrong (it probably just does something acceptable in our cases, or perhaps GetAddressOffset is never used in these situations).

**Comment by digitalinfinity** [comment]
FYI @curtisman @LouisLaf

**Comment by curtisman** [comment]
RE: the second issue for offsetof.  That is legal.  The "address" field is a member of  ProxyEntryPointInfo (not static).  The function is static. which is fine.

e.g. The follow build and runs fine with clang:
```C++
#include <stddef.h>
#include <stdio.h>

class C
{
public:
    void * field1;
    void * field2;
    static size_t GetOffsetOfField1() { return offsetof(C, field1); }
    static size_t GetOffsetOfField2() { return offsetof(C, field2); }
};

int main()
{
    printf("%d %d\n", (int)C::GetOffsetOfField1(), (int)C::GetOffsetOfField2());
}
```

**Comment by obastemur** [comment]
`Converting a pointer-to-member-function to a void ptr is illegal by C++ standard`[1] However current implementation was passing somehow on older Clang versions and VCC.

See https://github.com/Microsoft/ChakraCore/pull/726/commits/68482b2b4c51f25073ce5cc7e392be553726c049 for a potential fix. 

Summary of solution:
```c++
+        union address__ {
+            address__(void* ptr):ptr(ptr) {}
+            address__(Js::JavascriptMethod method):method(method) {}
+
+            void * ptr;
+            Js::JavascriptMethod method;
+        } address;
+        static_assert(sizeof(Js::JavascriptMethod) == sizeof(size_t), "This compiler / platform is not supported");
```

*[1]
From https://isocpp.org/wiki/faq/pointers-to-members#cant-cvt-memfnptr-to-voidptr

"pointers to member functions and pointers to data are not necessarily represented in 
the same way. A pointer to a member function might be a data structure rather than a single pointer. 
Think about it: if it’s pointing at a virtual function, it might not actually be pointing at a statically resolvable 
pile of code, so it might not even be a normal address — it might be a different data structure of some 
sort."

**Comment by xanlpz** [comment]
FWIW, these being static member functions does not make it different. They are equivalent to function pointers but those also cannot be cast to void*: https://isocpp.org/wiki/faq/pointers-to-members#cant-cvt-fnptr-to-voidptr

**Comment by obastemur** [comment]
After the discussion with @dreamer-dead, I have followed the generation of funPTR and this time included the parts only compiled under VS. saw `size_t` is being cast to `BYTE_PTR` and then funPTR. Resulting BYTE_PTR may fail to represent funPTR on cross platform (enum-aliasing / big endian..)

Alternative approach is to have voidPTR cast to funPTR on runtime. See https://github.com/obastemur/ChakraCore/commit/57cd553710b50a7a814f4abb95928e029fe9d051. (adress(jsMethod) is normalized to funPTR instead of voidPTR)

@curtisman ? enum-aliasing ? runtime casting? or ?

**Comment by obastemur** [comment]
IMO it's safe to close this now. @xanlpz ?

**Comment by xanlpz** [comment]
Yep, this seems to at least compile correctly here.
